[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "minerva-calc"
version = "1.0.0"

[tool.setuptools.packages.find]
where = ["src"] 
namespaces = false
